version: "3.8"

services:
  AlmsHVault:
    container_name: AlmsHVault
    hostname: AlmsHVault
    image: hashicorp/vault:latest
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${TOKEN_ID}
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_DEV_SERVER_MODE=true
    volumes:
      - ./data/vault_data:/vault/data
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - "40820:8200"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.AlmsHVault.rule=Host(`vault.localhost`)"
      - "traefik.http.routers.AlmsHVault.tls.certresolver=localresolver"
      - "traefik.http.routers.AlmsHVault.entrypoints=websecure"
      - "traefik.http.services.AlmsHVault.loadbalancer.server.port=8200"

volumes:
  vault_data:
    driver: local

networks:
  frontend:
    external: true
