---
name: Alms-Heimdall
services:
  AlmsHeimdall:
    container_name: AlmsHeimdall
    hostname: AlmsHeimdall
    image: lscr.io/linuxserver/heimdall:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./config:/config
    ports:
      - 280:80
      - 2443:443
    restart: unless-stopped
    networks:
      - frontend
    labels:
      # - traefik.http.routers.AlmsHeimdall.rule=Host(`heimdall.localhost`)
      - "traefik.enable=true"
      - "traefik.http.routers.AlmsHeimdall.rule=Host(`heimdall.localhost`)"
      - "traefik.http.routers.AlmsHeimdall.entrypoints=websecure"
      - "traefik.http.routers.AlmsHeimdall.tls.certresolver=localresolver"
      - "traefik.http.services.AlmsHeimdall.loadbalancer.server.port=80"

networks:
    frontend:
        external: true