---
name: Alms-It-Tools
services:
  AlmsItTools:
    container_name: AlmsItTools
    hostname: AlmsItTools
    image: 'corentinth/it-tools:latest'
    ports:
      - '8187:80'
    networks:
      - frontend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.AlmsItTools.rule=Host(`ittools.localhost`)"
      - "traefik.http.routers.AlmsItTools.entrypoints=websecure"
      - "traefik.http.routers.AlmsItTools.tls.certresolver=localresolver"
      - "traefik.http.services.AlmsItTools.loadbalancer.server.port=80"

networks:
    frontend:
        external: true

